name: Radare2 CI tree-sitter test

on:
  pull_request:
    paths:
      - 'shlr/tree-sitter/*'
      - 'shlr/tree-sitter/lib/*'
      - 'shlr/tree-sitter/lib/**/*'
      - 'shlr/radare2-shell-parser/*'
      - 'shlr/radare2-shell-parser/**/*'
    branches:
      - master
      - decompiler-refactoring

jobs:
  build:
    name: radare2-shell-parser-tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: cd shlr/radare2-shell-parser/ && npm install
    - name: Run tests
      run: |
        cd shlr/radare2-shell-parser
        export PATH=${PATH}:./node_modules/.bin
        tree-sitter generate
        tree-sitter test
