name: Radare2 CI - static build

on:
  schedule:
    # “At 00:00 on every 7th day-of-week.”
    - cron:  '0 0 * * */7'
  pull_request:
    branches:
    - master
    - decompiler-refactoring

jobs:
  build:
    name: ubuntu-static-tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      if: github.event_name != 'pull_request' || contains(github.event.pull_request.head.ref, 'static')
    - name: Checkout our Testsuite Binaries
      if: github.event_name != 'pull_request' || contains(github.event.pull_request.head.ref, 'static')
      uses: actions/checkout@v2
      with:
          repository: radareorg/radare2-testbins
          path: test/bins
    - name: Install static
      if: github.event_name != 'pull_request' || contains(github.event.pull_request.head.ref, 'static')
      run: |
        ./sys/static.sh
        sudo make symstall
    - name: Run tests
      if: github.event_name != 'pull_request' || contains(github.event.pull_request.head.ref, 'static')
      run: |
        r2 -v
        r2r -v
